[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "check-yaml", exclude = "^crates/unbill-tauri/ios/" },
  { id = "check-toml" },
  { id = "check-merge-conflict" },
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
  { id = "mixed-line-ending", args = ["--fix=lf"] },
]

[[repos]]
repo = "https://github.com/doublify/pre-commit-rust"
rev = "v1.0"
hooks = [
  { id = "fmt", args = ["--all", "--"] },
]

[[repos]]
repo = "https://github.com/hukkin/mdformat"
rev = "0.7.22"
hooks = [
  { id = "mdformat", exclude = "^unbill-docs/" },
]

[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "v1.7.7"
hooks = [
  { id = "actionlint" },
]
