[package]
name = "unbill-tui"
description = "Terminal UI for unbill."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "unbill-tui"
description = "Terminal UI for unbill."
path = "src/main.rs"

[dependencies]
build-info.workspace = true
unbill-build-info = { path = "../../crates/unbill-build-info" }
unbill-console = { path = "../../crates/unbill-console" }
unbill-asymmetric-channel = { path = "../../crates/unbill-asymmetric-channel", features = ["rpc"] }
unbill-storage = { path = "../../crates/unbill-storage" }
ratatui = "0.29"
crossterm = { version = "0.28", features = ["event-stream"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }
anyhow = { workspace = true }
tracing-subscriber = { workspace = true }
futures = "0.3"
base64 = "0.22"

[build-dependencies]
chrono.workspace = true
build-info-build.workspace = true
