[package]
name = "unbill-tauri"
description = "Tauri backend shell for unbill desktop."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
name = "unbill_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
unbill-console = { path = "../unbill-console" }
unbill-asymmetric-channel = { path = "../unbill-asymmetric-channel", features = ["local", "rpc"] }
unbill-store-fs = { path = "../unbill-store-fs" }
serde.workspace = true
tracing.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
tauri-plugin-deep-link = "2"
url = "2"
rustls = { version = "0.23", features = ["ring"] }
serde_json.workspace = true

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-updater = "2"
tauri-plugin-single-instance = "2"

[dev-dependencies]
unbill-store-memory = { path = "../unbill-store-memory" }
tokio.workspace = true
tracing-subscriber.workspace = true
